description: >
  Busqueda de confligtos con respecto a la rama base

parameters:
  modules:
    description: Path to the file for the list of the modules to build
    type: string
    default: /tmp/modules-filtered.txt
  shared-config:
    description: Path to the config providing shared resources (such as prerequisite jobs and common commands)
    type: string
    default: .circleci/config.yml
  continue-config:
    description: Path to the internally-used config for continuation
    type: string
    default: .circleci/continue-config.yml
steps:
  - run:
      name: Merge configs
      command: <<include(scripts/merge-modular-configs.sh)>>
       