description: >
  Busca y ejectua los job de los modulos que fueron modificados
# What will this job do?

parameters:
  modules:
    description: Directories which should be tested for changes; one directory per line. Each directory must have `.circleci/config.yml`.
    type: string
  base-revision:
    description: Revision to compare with the current HEAD
    type: string
    default: main
  modules-filtered:
    description: Path to the file where the filtered list of modules is generated
    type: string
    default: /tmp/modules-filtered.txt
  shared-config:
    description: Path to the config providing shared resources (such as prerequisite jobs and common commands)
    type: string
    default: .circleci/config.yml
  continue-config:
    description: Path to the internally-used config for continuation
    type: string
    default: .circleci/continue-config.yml
docker:
  - image: cimg/python:3.9
steps:
  - checkout
  - run:
      name: Install yq
      command: pip install yq
  - list-changed-modules:
      modules: << parameters.modules >>
      modules-filtered: << parameters.modules-filtered >>
      base-revision: << parameters.base-revision >>
  - merge-modular-configs:
      modules: << parameters.modules-filtered >>
      shared-config: << parameters.shared-config >>
      continue-config: << parameters.continue-config >>
  - continuation/continue:
      configuration_path: << parameters.continue-config >>
      parameters: '{"run-setup":false}'